### ISSUE TITLE
part1 dataset 百度云提取码不正确

### ISSUE THREAD

**Issue by Gzzgz** [zhengxyun/PKU-DyMVHumans#1]
非常棒非常好的工作！！！
![图片](https://github.com/zhengxyun/PKU-DyMVHumans/assets/15968092/23d8a717-eb03-45e4-922a-1784f24d1d1a)
ke否更新一下这个提取码呢，好像不对
十分感谢

**Comment by zhengxyun** [comment]
您好，感谢对本工作的关注与支持！

数据集下载链接已更新

**Comment by Gzzgz** [comment]
👍🏻
