### ISSUE TITLE
[Question] How to get time?

### ISSUE THREAD

**Issue by WongiPark0628** [zhengxyun/PKU-DyMVHumans#2]
Hello. First, thank you for making good dataset. 
I want to apply D-NeRF, but there's no time information in the JSON file. Can you tell me how to extract the information? 
I'll share the results afterwards. Thank you.

**Comment by zhengxyun** [comment]
Our dataset provided the multi-view videos which are captured by numerous fixed pose cameras. 
All the ./videos/*.mp4 files are the synchronized videos for each camera. 

To specify dynamic scenes with time information, it may be possible to build DNeRF-like data by a single camera. More specifically, you may refer to [issue #106](https://github.com/hustvl/4DGaussians/issues/106) of  [4DGaussians](https://github.com/hustvl/4DGaussians). 

I hope this helps.

**Comment by WongiPark0628** [comment]
Thank you for your advice. It was very helpful. Thank you.
